version: "3.9"

services:
  frontend:
    container_name: video-download-youtube-web-front
    build:
      context: ./frontend
    ports:
      - "5173:80"

  backend:
    container_name: video-download-youtube-web-backend
    build:
      context: ./backend
    ports:
      - "8000:8000"
